

#核心配置.
github:
      client:
             clientId: ad2abbc19b6c5f0ed117
             clientSecret: 26db88a4dfc34cebaf196e68761c1294ac4ce265
             accessTokenUri: https://github.com/login/oauth/access_token
             userAuthorizationUri: https://github.com/login/oauth/authorize
             clientAuthenticationScheme: form
             tokenName: tokenName
             authenticationScheme: query
      resource:
             userInfoUri: https://api.github.com/user
